export const statsKeyWord = {
  ATK: "공격력",
  DEF: "방어력",
  STR: "힘",
  DEX: "민첩",
  INT: "지능",
  WILL: "의지",
  LUCK: "행운",
  HP: "최대 생명력",
  STAMINA: "최대 스태미나",
  ATK_Speed: "공격 속도",
  ATK_Absolute: "추가피해",
  Critical: "크리티컬",
  CritFactor: "크리티컬 피해량",
  Res_Critical: "크리티컬 저항",
  Balance: "밸런스",
  ATK_LimitOver: "공격력 제한 해제",
  Immunity: "대항력",
};
